apiVersion: batch/v1
kind: CronJob
metadata:
  name: push-repos
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: "0 0 * * 2"
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
          - name: task
            image: mirror-public-gitea-to-github:latest
            imagePullPolicy: Always
          restartPolicy: Never